### ISSUE TITLE
android 4.4 miui6 崩溃，日志如下

### ISSUE THREAD

**Issue by gfuil** [lihangleo2/ShadowLayout#105]
java.lang.NoSuchMethodError: android.graphics.Path.addRoundRect
        at com.lihang.ShadowLayout.dispatchDraw(ShadowLayout.java:1027)
        at android.view.View.draw(View.java:14496)
        at android.widget.FrameLayout.draw(FrameLayout.java:472)
        at android.view.View.getDisplayList(View.java:13390)
        at android.view.View.getDisplayList(View.java:13432)
        at android.view.View.draw(View.java:14210)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.getDisplayList(View.java:13385)
        at android.view.View.getDisplayList(View.java:13432)
        at android.view.View.draw(View.java:14210)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.getDisplayList(View.java:13385)
        at android.view.View.getDisplayList(View.java:13432)
        at android.view.View.draw(View.java:14210)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.draw(View.java:14496)
        at android.widget.FrameLayout.draw(FrameLayout.java:472)
        at android.view.View.getDisplayList(View.java:13390)
        at android.view.View.getDisplayList(View.java:13432)
        at android.view.View.draw(View.java:14210)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.getDisplayList(View.java:13385)
        at android.view.View.getDisplayList(View.java:13432)
        at android.view.View.draw(View.java:14210)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.getDisplayList(View.java:13385)
        at android.view.View.getDisplayList(View.java:13432)
        at android.view.View.draw(View.java:14210)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.getDisplayList(View.java:13385)
        at android.view.View.getDisplayList(View.java:13432)
        at android.view.View.draw(View.java:14210)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.draw(View.java:14496)
        at android.widget.FrameLayout.draw(FrameLayout.java:472)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2326)
        at android.view.View.getDisplayList(View.java:13390)
        at android.view.View.getDisplayList(View.java:13432)
        at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1577)
        at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1451)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2420)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2292)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1922)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1039)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5648)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
        at android.view.Choreographer.doFrame(Choreographer.java:544)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5111)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by lihangleo2** [comment]
不会向下兼容。举个例子 见过现在ai的软件和技术  支持4.4手机的么？感谢你的支持
