### ISSUE TITLE
code设置阴影报错

### ISSUE THREAD

**Issue by LayneCui** [lihangleo2/ShadowLayout#14]
ShadowLayout 中控件是固定大小的，xml 设置背景颜色起作用，代码设置会报错

<com.lihang.ShadowLayout
android:id="@+id/shadow2"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
app:hl_cornerRadius="4dp"
app:hl_dx="2dp"
app:hl_dy="3dp"
app:hl_leftShow="false"
app:hl_topShow="false"
app:hl_shadowBackColor="#fff"
app:hl_shadowLimit="3dp"
app:layout_constraintTop_toTopOf="parent"
app:layout_constraintLeft_toRightOf="@id/shadow1"
app:layout_constraintRight_toLeftOf="@id/shadow4"
>

    <com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/img2"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:roundedCornerRadius="4dp"
            fresco:placeholderImage="@drawable/bg_r4_color_99_black" />

    <ImageView
            android:id="@+id/imv_vip2"
            android:layout_width="29dp"
            android:layout_height="13dp"
            android:src="@mipmap/icon_home_tag_vip_small"
            android:visibility="gone"/>

    <TextView
            android:id="@+id/tv_name2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="学院"
            android:textColor="@color/white"
            android:textSize="16sp"
            android:textStyle="bold"
            android:layout_marginTop="11dp"
            android:layout_marginLeft="13dp"/>

    <TextView
            android:id="@+id/tv_study_count2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="222"
            android:textColor="@color/white"
            android:textSize="10sp"
            android:layout_below="@+id/tv_name2"
            android:layout_marginTop="3dp"
            android:layout_marginLeft="17dp"/>
</RelativeLayout>
</com.lihang.ShadowLayout>

**Comment by LayneCui** [comment]
我写了个 demo 试了一下，还是报同样的错误：

2019-10-12 08:42:11.720 18174-18174/com.chazuo.college.enterprise E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.chazuo.college.enterprise, PID: 18174
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chazuo.college.enterprise/com.chazuo.college.enterprise.test.Test2Activity}: java.lang.IllegalArgumentException: width and height must be > 0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3047)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1033)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1000)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:950)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:911)
        at com.lihang.ShadowLayout.createShadowBitmap(ShadowLayout.java:235)
        at com.lihang.ShadowLayout.setBackgroundCompat(ShadowLayout.java:194)
        at com.lihang.ShadowLayout.setmShadowColor(ShadowLayout.java:110)
        at com.chazuo.college.enterprise.test.Test2Activity.onCreate(Test2Activity.java:30)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source:24)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3027)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-10-12 08:42:11.721 18174-18174/com.chazuo.college.enterprise E/CrashHandler: In thread: Thread[main,5,main]
    UncaughtException detected: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chazuo.college.enterprise/com.chazuo.college.enterprise.test.Test2Activity}: java.lang.IllegalArgumentException: width and height must be > 0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3047)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1033)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1000)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:950)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:911)
        at com.lihang.ShadowLayout.createShadowBitmap(ShadowLayout.java:235)
        at com.lihang.ShadowLayout.setBackgroundCompat(ShadowLayout.java:194)
        at com.lihang.ShadowLayout.setmShadowColor(ShadowLayout.java:110)
        at com.chazuo.college.enterprise.test.Test2Activity.onCreate(Test2Activity.java:30)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source:24)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3027)




代码如下：

<RelativeLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:fresco="http://schemas.android.com/tools"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="200dp"
        android:layout_height="200dp"
        tools:context="com.chazuo.college.enterprise.test.Test2Activity">

    <com.lihang.ShadowLayout
            android:id="@+id/shadow1"
            android:layout_width="100dp"
            android:layout_height="100dp"
            app:hl_cornerRadius="4dp"
            app:hl_dx="2dp"
            app:hl_dy="3dp"
            app:hl_leftShow="false"
            app:hl_shadowBackColor="#fff"
            app:hl_shadowColor="#aaCCE6FF"
            app:hl_shadowLimit="3dp"
            app:hl_topShow="false"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintTop_toTopOf="parent">

        <TextView
                android:layout_width="100dp"
                android:layout_height="100dp"
                android:text="11111"/>

    </com.lihang.ShadowLayout>
</RelativeLayout>


code：

protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_test2);

        ShadowLayout shadowLayout = findViewById(R.id.shadow1);

        shadowLayout.setmShadowColor(Color.argb(188,255,0,0));

//        getMerageData();
    }

**Comment by lihangleo2** [comment]
是这样的，当你页面还未渲染的的时候，ShadowLayout ，getWidth(),getHeight()，获取不到宽和高。如果途中不需要改变颜色值，不推荐在代码里改变颜色值，我加这个方法是为了展示。如果途中点击了什么操作或按钮，代码改变颜色值是OK的。或者在onCreate里，用handler来个延迟操作也行，异或是再往空间里加一个主动传入宽高的方法，创建阴影的背景bitmap。感谢你的支持和issue，后期我会把这块优化下
```java
public void setmShadowColor(int mShadowColor) {
        this.mShadowColor = mShadowColor;
        setBackgroundCompat(getWidth(), getHeight());
    }
```
