### ISSUE TITLE
use in recycle view

### ISSUE THREAD

**Issue by henryhui-pure** [lihangleo2/ShadowLayout#22]
在recycle view不能更換shadow 顏色嗎 ?

I will get this error when changing color in adapter

 Process: com.pure.international.pure360, PID: 25186
    java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1252)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1219)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1169)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1130)
        at com.lihang.ShadowLayout.createShadowBitmap(ShadowLayout.java:244)
        at com.lihang.ShadowLayout.setBackgroundCompat(ShadowLayout.java:194)
        at com.lihang.ShadowLayout.setmShadowColor(ShadowLayout.java:110)
        at com.pure.international.pure360.adapter.ClassViewAdapter.onBindViewHolder(ClassViewAdapter.java:123)

My code in adapter 
    if(FavouriteClassDbController.checkIfExist(item.getId())) {
            viewHolder.getIvFav().setVisibility(View.VISIBLE);
            if (item.getCategory().equals("Yoga")) {
                viewHolder.getLlContainer().setmShadowColor(R.color.shadow_yoga_blue);
            }else if (item.getCategory().equals("FUZE")) {
                viewHolder.getLlContainer().setmShadowColor( R.color.shadow_fuze_orange);
            }else {
                viewHolder.getLlContainer().setmShadowColor (R.color.shadow_fitness_red);
            }
        } else {
            viewHolder.getLlContainer().setmShadowColor(R.color.shadow_default);
            viewHolder.getIvFav().setVisibility(View.GONE);
        }

**Comment by lihangleo2** [comment]
shadowLayout相当于一个ViewGroup。可以修改的。但是有个问题是他的背景颜色值是在底层，如果你再recycleView的item里，也就是shadowLayout的子view了设置了background的话，会覆盖掉shadowLayout的背景
