### ISSUE TITLE
放到recyclerView中使用滑动多页后会造成bitmap发生OOM

### ISSUE THREAD

**Issue by yangchong211** [lihangleo2/ShadowLayout#3]
- 崩溃日志
```
java.lang.OutOfMemoryError: Failed to allocate a 1190700 byte allocation with 389392 free bytes and 380KB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
        at com.cheoo.app.view.shadow.ShadowLayout.createShadowBitmap(ShadowLayout.java:242)
        at com.cheoo.app.view.shadow.ShadowLayout.setBackgroundCompat(ShadowLayout.java:195)
        at com.cheoo.app.view.shadow.ShadowLayout.onSizeChanged(ShadowLayout.java:132)
        at android.view.View.sizeChange(View.java:17824)
        at android.view.View.setFrame(View.java:17786)
        at android.view.View.layout(View.java:17694)
        at android.view.ViewGroup.layout(ViewGroup.java:5736)
        at android.support.v7.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9322)
        at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1699)
        at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:683)
        at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:605)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
        at android.view.View.measure(View.java:19917)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6244)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19917)
        at android.support.v7.widget.GridLayoutManager.measureChildWithDecorationsAndMargin(GridLayoutManager.java:761)
        at android.support.v7.widget.GridLayoutManager.measureChild(GridLayoutManager.java:732)
        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:593)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:17697)
        at android.view.ViewGroup.layout(ViewGroup.java:5736)
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:691)
        at android.view.View.layout(View.java:17697)
        at android.view.ViewGroup.layout(ViewGroup.java:5736)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17697)
        at android.view.ViewGroup.layout(ViewGroup.java:5736)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17697)
        at android.view.ViewGroup.layout(ViewGroup.java:5736)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17697)
        at android.view.ViewGroup.layout(ViewGroup.java:5736)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17697)
        at android.view.ViewGroup.layout(ViewGroup.java:5736)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
        at android.view.View.layout(View.java:17697)
        at android.view.ViewGroup.layout(ViewGroup.java:5736)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
```
- 除了用缓存的方法存取bitmap对象以外，楼主可还有什么其他的好方案？

**Comment by lihangleo2** [comment]
稍等，我发布2.0版本、我测过缓存，也测过recycleView，bitmap没有引用，且recycleView有复用机制，recycleView列表满一页以后，内存几乎不抖动。我试是这样的。稍后我把这个项目完善起来

**Comment by lihangleo2** [comment]
而且这样创建的一张bitmap，最大的页就500KB多。你看看是不是你哪里写的有问题

**Comment by yangchong211** [comment]
应该不会，我是用cardView的时候是不会出现OOM的。我用在了瀑布流中，并且瀑布流中大概有10种不同类型的布局，况且bitmap3.0之后建议不要手动处理回收，除了你知道不用呢。因此在recyclerView，虽然有自动回收，但还是会频繁创建阴影效果中的bitmap，你滑动超过三四十个页面试试，就用内存监测工具看看就可以发现问题呢……

**Comment by lihangleo2** [comment]
2.0已经可以动态修改了。滑动seekBar 创建的不止是30,40张。是上千张了。内存监控已经在掘金说明

杨充 <notifications@github.com> 于2019年8月9日周五 上午10:56写道：
